export default function getPeriod() {
  const SEMESTER_GANJIL = "SEMESTER GANJIL TA 2024/2025";
  const SEMESTER_GENAP = "SEMESTER GENAP TA 2024/2025";
  const SEMESTER_GANJIL_SLUG = "2024/2025-1";
  const SEMESTER_GENAP_SLUG = "2024/2025-2";
  const CURRENT_PERIOD = SEMESTER_GANJIL;
  const CURRENT_PERIOD_SLUG = SEMESTER_GANJIL_SLUG;

  return {
    SEMESTER_GANJIL,
    SEMESTER_GENAP,
    SEMESTER_GANJIL_SLUG,
    SEMESTER_GENAP_SLUG,
    CURRENT_PERIOD,
    CURRENT_PERIOD_SLUG,
  };
}
